id: IA9FE0FA9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T23:58:38+00:00'
last_modified: '2022-06-08T04:22:49.035281+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20390
  title: བྱང་ཆུབ་སེམས་དཔའ་རྟག་ངུའི་རྟོགས་བརྗོད་སྙན་དངགས་དཔག་བསམ་གྱི་ལྗོན་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '0040':
      image_group_id: I4701
      title: ''
      total_pages: 310
      order: 1
      base_file: 0040.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
